
CREATE TABLE "Albums"
(
    AlbumId INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    Title TEXT(160) NOT NULL,
    ArtistId INTEGER NOT NULL,
	FOREIGN KEY (ArtistId) REFERENCES Albums (AlbumId)  ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE "Artists"
(
    ArtistId INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    Name TEXT(120) NOT NULL
);






INSERT INTO Artists (Name) VALUES ('AC/DC');
INSERT INTO Artists (Name) VALUES ('Accept');
INSERT INTO Artists (Name) VALUES ('Aerosmith');
INSERT INTO Artists (Name) VALUES ('Alanis Morissette');
INSERT INTO Artists (Name) VALUES ('Alice In Chains');
INSERT INTO Artists (Name) VALUES ('Antônio Carlos Jobim');
INSERT INTO Artists (Name) VALUES ('Apocalyptica');
INSERT INTO Artists (Name) VALUES ('Audioslave');
INSERT INTO Artists (Name) VALUES ('BackBeat');
INSERT INTO Artists (Name) VALUES ('Billy Cobham');
INSERT INTO Artists (Name) VALUES ('Black Label Society');
INSERT INTO Artists (Name) VALUES ('Black Sabbath');
INSERT INTO Artists (Name) VALUES ('Body Count');
INSERT INTO Artists (Name) VALUES ('Bruce Dickinson');
INSERT INTO Artists (Name) VALUES ('Buddy Guy');
INSERT INTO Artists (Name) VALUES ('Caetano Veloso');
INSERT INTO Artists (Name) VALUES ('Chico Buarque');
INSERT INTO Artists (Name) VALUES ('Chico Science & Nação Zumbi');
INSERT INTO Artists (Name) VALUES ('Cidade Negra');
INSERT INTO Artists (Name) VALUES ('Cláudio Zoli');
INSERT INTO Artists (Name) VALUES ('Various Artists');
INSERT INTO Artists (Name) VALUES ('Led Zeppelin');
INSERT INTO Artists (Name) VALUES ('Frank Zappa & Captain Beefheart');
INSERT INTO Artists (Name) VALUES ('Marcos Valle');
INSERT INTO Artists (Name) VALUES ('Milton Nascimento & Bebeto');
INSERT INTO Artists (Name) VALUES ('Azymuth');
INSERT INTO Artists (Name) VALUES ('Gilberto Gil');
INSERT INTO Artists (Name) VALUES ('João Gilberto');
INSERT INTO Artists (Name) VALUES ('Bebel Gilberto');
INSERT INTO Artists (Name) VALUES ('Jorge Vercilo');
INSERT INTO Artists (Name) VALUES ('Baby Consuelo');
INSERT INTO Artists (Name) VALUES ('Ney Matogrosso');
INSERT INTO Artists (Name) VALUES ('Luiz Melodia');
INSERT INTO Artists (Name) VALUES ('Nando Reis');
INSERT INTO Artists (Name) VALUES ('Pedro Luís & A Parede');
INSERT INTO Artists (Name) VALUES ('O Rappa');
INSERT INTO Artists (Name) VALUES ('Ed Motta');
INSERT INTO Artists (Name) VALUES ('Banda Black Rio');
INSERT INTO Artists (Name) VALUES ('Fernanda Porto');
INSERT INTO Artists (Name) VALUES ('Os Cariocas');
INSERT INTO Artists (Name) VALUES ('Elis Regina');
INSERT INTO Artists (Name) VALUES ('Milton Nascimento');
INSERT INTO Artists (Name) VALUES ('A Cor Do Som');
INSERT INTO Artists (Name) VALUES ('Kid Abelha');
INSERT INTO Artists (Name) VALUES ('Sandra De Sá');
INSERT INTO Artists (Name) VALUES ('Jorge Ben');
INSERT INTO Artists (Name) VALUES ('Hermeto Pascoal');
INSERT INTO Artists (Name) VALUES ('Barão Vermelho');
INSERT INTO Artists (Name) VALUES ('Edson, DJ Marky & DJ Patife Featuring Fernanda Porto');
INSERT INTO Artists (Name) VALUES ('Metallica');
INSERT INTO Artists (Name) VALUES ('Queen');
INSERT INTO Artists (Name) VALUES ('Kiss');
INSERT INTO Artists (Name) VALUES ('Spyro Gyra');
INSERT INTO Artists (Name) VALUES ('Green Day');
INSERT INTO Artists (Name) VALUES ('David Coverdale');
INSERT INTO Artists (Name) VALUES ('Gonzaguinha');
INSERT INTO Artists (Name) VALUES ('Os Mutantes');
INSERT INTO Artists (Name) VALUES ('Deep Purple');
INSERT INTO Artists (Name) VALUES ('Santana');
INSERT INTO Artists (Name) VALUES ('Santana Feat. Dave Matthews');
INSERT INTO Artists (Name) VALUES ('Santana Feat. Everlast');
INSERT INTO Artists (Name) VALUES ('Santana Feat. Rob Thomas');
INSERT INTO Artists (Name) VALUES ('Santana Feat. Lauryn Hill & Cee-Lo');
INSERT INTO Artists (Name) VALUES ('Santana Feat. The Project G&B');
INSERT INTO Artists (Name) VALUES ('Santana Feat. Maná');
INSERT INTO Artists (Name) VALUES ('Santana Feat. Eagle-Eye Cherry');
INSERT INTO Artists (Name) VALUES ('Santana Feat. Eric Clapton');
INSERT INTO Artists (Name) VALUES ('Miles Davis');
INSERT INTO Artists (Name) VALUES ('Gene Krupa');
INSERT INTO Artists (Name) VALUES ('Toquinho & Vinícius');
INSERT INTO Artists (Name) VALUES ('Vinícius De Moraes & Baden Powell');
INSERT INTO Artists (Name) VALUES ('Vinícius De Moraes');
INSERT INTO Artists (Name) VALUES ('Vinícius E Qurteto Em Cy');
INSERT INTO Artists (Name) VALUES ('Vinícius E Odette Lara');
INSERT INTO Artists (Name) VALUES ('Vinicius, Toquinho & Quarteto Em Cy');
INSERT INTO Artists (Name) VALUES ('Creedence Clearwater Revival');
INSERT INTO Artists (Name) VALUES ('Cássia Eller');
INSERT INTO Artists (Name) VALUES ('Def Leppard');
INSERT INTO Artists (Name) VALUES ('Dennis Chambers');
INSERT INTO Artists (Name) VALUES ('Djavan');
INSERT INTO Artists (Name) VALUES ('Eric Clapton');
INSERT INTO Artists (Name) VALUES ('Faith No More');
INSERT INTO Artists (Name) VALUES ('Falamansa');
INSERT INTO Artists (Name) VALUES ('Foo Fighters');
INSERT INTO Artists (Name) VALUES ('Frank Sinatra');
INSERT INTO Artists (Name) VALUES ('Funk Como Le Gusta');
INSERT INTO Artists (Name) VALUES ('Godsmack');
INSERT INTO Artists (Name) VALUES ('Guns N'' Roses');
INSERT INTO Artists (Name) VALUES ('Incognito');
INSERT INTO Artists (Name) VALUES ('Iron Maiden');
INSERT INTO Artists (Name) VALUES ('James Brown');
INSERT INTO Artists (Name) VALUES ('Jamiroquai');
INSERT INTO Artists (Name) VALUES ('JET');
INSERT INTO Artists (Name) VALUES ('Jimi Hendrix');
INSERT INTO Artists (Name) VALUES ('Joe Satriani');
INSERT INTO Artists (Name) VALUES ('Jota Quest');
INSERT INTO Artists (Name) VALUES ('João Suplicy');
INSERT INTO Artists (Name) VALUES ('Judas Priest');
INSERT INTO Artists (Name) VALUES ('Legião Urbana');
INSERT INTO Artists (Name) VALUES ('Lenny Kravitz');


INSERT INTO Albums (Title, ArtistId) VALUES ('For Those About To Rock We Salute You', 1);
INSERT INTO Albums (Title, ArtistId) VALUES ('Balls to the Wall', 2);
INSERT INTO Albums (Title, ArtistId) VALUES ('Restless and Wild', 2);
INSERT INTO Albums (Title, ArtistId) VALUES ('Let There Be Rock', 1);
INSERT INTO Albums (Title, ArtistId) VALUES ('Big Ones', 3);
INSERT INTO Albums (Title, ArtistId) VALUES ('Jagged Little Pill', 4);
INSERT INTO Albums (Title, ArtistId) VALUES ('Facelift', 5);
INSERT INTO Albums (Title, ArtistId) VALUES ('Warner 25 Anos', 6);
INSERT INTO Albums (Title, ArtistId) VALUES ('Plays Metallica By Four Cellos', 7);
INSERT INTO Albums (Title, ArtistId) VALUES ('Audioslave', 8);
INSERT INTO Albums (Title, ArtistId) VALUES ('Out Of Exile', 8);
INSERT INTO Albums (Title, ArtistId) VALUES ('BackBeat Soundtrack', 9);
INSERT INTO Albums (Title, ArtistId) VALUES ('The Best Of Billy Cobham', 10);
INSERT INTO Albums (Title, ArtistId) VALUES ('Alcohol Fueled Brewtality Live! [Disc 1]', 11);
INSERT INTO Albums (Title, ArtistId) VALUES ('Alcohol Fueled Brewtality Live! [Disc 2]', 11);
INSERT INTO Albums (Title, ArtistId) VALUES ('Black Sabbath', 12);
INSERT INTO Albums (Title, ArtistId) VALUES ('Black Sabbath Vol. 4 (Remaster)', 12);
INSERT INTO Albums (Title, ArtistId) VALUES ('Body Count', 13);
INSERT INTO Albums (Title, ArtistId) VALUES ('Chemical Wedding', 14);
INSERT INTO Albums (Title, ArtistId) VALUES ('The Best Of Buddy Guy - The Millenium Collection', 15);
INSERT INTO Albums (Title, ArtistId) VALUES ('Prenda Minha', 16);
INSERT INTO Albums (Title, ArtistId) VALUES ('Sozinho Remix Ao Vivo', 16);
INSERT INTO Albums (Title, ArtistId) VALUES ('Minha Historia', 17);
INSERT INTO Albums (Title, ArtistId) VALUES ('Afrociberdelia', 18);
INSERT INTO Albums (Title, ArtistId) VALUES ('Da Lama Ao Caos', 18);
INSERT INTO Albums (Title, ArtistId) VALUES ('Acústico MTV [Live]', 19);
INSERT INTO Albums (Title, ArtistId) VALUES ('Cidade Negra - Hits', 19);
INSERT INTO Albums (Title, ArtistId) VALUES ('Na Pista', 20);
INSERT INTO Albums (Title, ArtistId) VALUES ('Axé Bahia 2001', 21);
INSERT INTO Albums (Title, ArtistId) VALUES ('BBC Sessions [Disc 1] [Live]', 22);
INSERT INTO Albums (Title, ArtistId) VALUES ('Bongo Fury', 23);
INSERT INTO Albums (Title, ArtistId) VALUES ('Carnaval 2001', 21);
INSERT INTO Albums (Title, ArtistId) VALUES ('Chill: Brazil (Disc 1)', 24);
INSERT INTO Albums (Title, ArtistId) VALUES ('Chill: Brazil (Disc 2)', 6);
INSERT INTO Albums (Title, ArtistId) VALUES ('Garage Inc. (Disc 1)', 50);
INSERT INTO Albums (Title, ArtistId) VALUES ('Greatest Hits II', 51);
INSERT INTO Albums (Title, ArtistId) VALUES ('Greatest Kiss', 52);
INSERT INTO Albums (Title, ArtistId) VALUES ('Heart of the Night', 53);
INSERT INTO Albums (Title, ArtistId) VALUES ('International Superhits', 54);
INSERT INTO Albums (Title, ArtistId) VALUES ('Into The Light', 55);
INSERT INTO Albums (Title, ArtistId) VALUES ('Meus Momentos', 56);
INSERT INTO Albums (Title, ArtistId) VALUES ('Minha História', 57);
INSERT INTO Albums (Title, ArtistId) VALUES ('MK III The Final Concerts [Disc 1]', 58);
INSERT INTO Albums (Title, ArtistId) VALUES ('Physical Graffiti [Disc 1]', 22);
INSERT INTO Albums (Title, ArtistId) VALUES ('Sambas De Enredo 2001', 21);
INSERT INTO Albums (Title, ArtistId) VALUES ('Supernatural', 59);
INSERT INTO Albums (Title, ArtistId) VALUES ('The Best of Ed Motta', 37);
INSERT INTO Albums (Title, ArtistId) VALUES ('The Essential Miles Davis [Disc 1]', 68);
INSERT INTO Albums (Title, ArtistId) VALUES ('The Essential Miles Davis [Disc 2]', 68);
INSERT INTO Albums (Title, ArtistId) VALUES ('The Final Concerts (Disc 2)', 58);
INSERT INTO Albums (Title, ArtistId) VALUES ('Up An'' Atom', 69);
INSERT INTO Albums (Title, ArtistId) VALUES ('Vinícius De Moraes - Sem Limite', 70);
INSERT INTO Albums (Title, ArtistId) VALUES ('Vozes do MPB', 21);
INSERT INTO Albums (Title, ArtistId) VALUES ('Chronicle, Vol. 1', 76);
INSERT INTO Albums (Title, ArtistId) VALUES ('Chronicle, Vol. 2', 76);
INSERT INTO Albums (Title, ArtistId) VALUES ('Cássia Eller - Coleção Sem Limite [Disc 2]', 77);
INSERT INTO Albums (Title, ArtistId) VALUES ('Cássia Eller - Sem Limite [Disc 1]', 77);
INSERT INTO Albums (Title, ArtistId) VALUES ('Come Taste The Band', 58);
INSERT INTO Albums (Title, ArtistId) VALUES ('Deep Purple In Rock', 58);
INSERT INTO Albums (Title, ArtistId) VALUES ('Fireball', 58);
INSERT INTO Albums (Title, ArtistId) VALUES ('Knocking at Your Back Door: The Best Of Deep Purple in the 80''s', 58);
INSERT INTO Albums (Title, ArtistId) VALUES ('Machine Head', 58);
INSERT INTO Albums (Title, ArtistId) VALUES ('Purpendicular', 58);
INSERT INTO Albums (Title, ArtistId) VALUES ('Slaves And Masters', 58);
INSERT INTO Albums (Title, ArtistId) VALUES ('Stormbringer', 58);
INSERT INTO Albums (Title, ArtistId) VALUES ('The Battle Rages On', 58);
INSERT INTO Albums (Title, ArtistId) VALUES ('Vault: Def Leppard''s Greatest Hits', 78);
INSERT INTO Albums (Title, ArtistId) VALUES ('Outbreak', 79);
INSERT INTO Albums (Title, ArtistId) VALUES ('Djavan Ao Vivo - Vol. 02', 80);
INSERT INTO Albums (Title, ArtistId) VALUES ('Djavan Ao Vivo - Vol. 1', 80);
INSERT INTO Albums (Title, ArtistId) VALUES ('Elis Regina-Minha História', 41);
INSERT INTO Albums (Title, ArtistId) VALUES ('The Cream Of Clapton', 81);
INSERT INTO Albums (Title, ArtistId) VALUES ('Unplugged', 81);
INSERT INTO Albums (Title, ArtistId) VALUES ('Album Of The Year', 82);
INSERT INTO Albums (Title, ArtistId) VALUES ('Angel Dust', 82);
INSERT INTO Albums (Title, ArtistId) VALUES ('King For A Day Fool For A Lifetime', 82);
INSERT INTO Albums (Title, ArtistId) VALUES ('The Real Thing', 82);
INSERT INTO Albums (Title, ArtistId) VALUES ('Deixa Entrar', 83);
INSERT INTO Albums (Title, ArtistId) VALUES ('In Your Honor [Disc 1]', 84);
INSERT INTO Albums (Title, ArtistId) VALUES ('In Your Honor [Disc 2]', 84);
INSERT INTO Albums (Title, ArtistId) VALUES ('One By One', 84);
INSERT INTO Albums (Title, ArtistId) VALUES ('The Colour And The Shape', 84);
INSERT INTO Albums (Title, ArtistId) VALUES ('My Way: The Best Of Frank Sinatra [Disc 1]', 85);
INSERT INTO Albums (Title, ArtistId) VALUES ('Roda De Funk', 86);
INSERT INTO Albums (Title, ArtistId) VALUES ('As Canções de Eu Tu Eles', 27);
INSERT INTO Albums (Title, ArtistId) VALUES ('Quanta Gente Veio Ver (Live)', 27);
INSERT INTO Albums (Title, ArtistId) VALUES ('Quanta Gente Veio ver--Bônus De Carnaval', 27);
INSERT INTO Albums (Title, ArtistId) VALUES ('Faceless', 87);
INSERT INTO Albums (Title, ArtistId) VALUES ('American Idiot', 54);
INSERT INTO Albums (Title, ArtistId) VALUES ('Appetite for Destruction', 88);
INSERT INTO Albums (Title, ArtistId) VALUES ('Use Your Illusion I', 88);
INSERT INTO Albums (Title, ArtistId) VALUES ('Use Your Illusion II', 88);
INSERT INTO Albums (Title, ArtistId) VALUES ('Blue Moods', 89);
INSERT INTO Albums (Title, ArtistId) VALUES ('A Matter of Life and Death', 90);
INSERT INTO Albums (Title, ArtistId) VALUES ('A Real Dead One', 90);
INSERT INTO Albums (Title, ArtistId) VALUES ('A Real Live One', 90);
INSERT INTO Albums (Title, ArtistId) VALUES ('Brave New World', 90);
INSERT INTO Albums (Title, ArtistId) VALUES ('Dance Of Death', 90);
INSERT INTO Albums (Title, ArtistId) VALUES ('Fear Of The Dark', 90);
